// eslint-disable-next-line no-shadow
export enum PARSER_TYPE {
  TWITTER_PARSER = 'TWITTER',
  TWITTER_API_PARSER = 'TWITTER_API',
  REDDIT_PARSER = 'REDDIT',
  FORUM_PARSER = 'FORUM_PARSER',
  HEURISTIC_FORUM_PARSER = 'HEURISTIC_FORUM_PARSER',
  UNIVERSAL_PARSER = 'UNIVERSAL_PARSER',
  PUPPETEER_PARSER = 'PUPPETEER_PARSER',
  AIMLEAP_PARSER = 'AIMLEAP',
  COGNIZANT = 'COGNIZANT',
}
