import moment from 'moment';
import { ElementHandle, Page } from 'puppeteer';
import PuppeteerParser from '../lib/parsers/puppeteerParser';
import { Post } from '../lib/types';

const baseURLPrefix = 'https://www.mk-mode.com';
const baseURLSuffix = '/rails/disaster';

const referenceMap = new Map([
  ['伊予消防本部', 'http://119iyo.jp/saigai/'],
  ['長崎市消防局', 'http://119.city.nagasaki.nagasaki.jp/saigai/'],
  ['旭市消防本部', 'http://business4.plala.or.jp/chiba119/web/asahi/annai.html'],
  ['安房広域消防本部', 'http://business4.plala.or.jp/chiba119/web/awa/annai.html'],
  ['千葉市消防局', 'http://business4.plala.or.jp/chiba119/web/chiba/annai.html'],
  ['長生広域消防本部', 'http://business4.plala.or.jp/chiba119/web/chosei/annai.html'],
  ['銚子市消防本部', 'http://business4.plala.or.jp/chiba119/web/choshi/annai.html'],
  ['富津市消防本部', 'http://business4.plala.or.jp/chiba119/web/futtsu/annai.html'],
  ['市原市消防局', 'http://business4.plala.or.jp/chiba119/web/ichihara/annai.html'],
  ['印西地区消防本部', 'http://business4.plala.or.jp/chiba119/web/inzai/annai.html'],
  ['夷隅広域消防本部', 'http://business4.plala.or.jp/chiba119/web/isumi/annai.html'],
  ['香取広域消防本部', 'http://business4.plala.or.jp/chiba119/web/katori/annai.html'],
  ['君津市消防本部', 'http://business4.plala.or.jp/chiba119/web/kimitsu/annai.html'],
  ['木更津市消防本部', 'http://business4.plala.or.jp/chiba119/web/kisarazu/annai.html'],
  ['成田市消防本部', 'http://business4.plala.or.jp/chiba119/web/narita/annai.html'],
  ['栄町消防本部', 'http://business4.plala.or.jp/chiba119/web/sakae/annai.html'],
  ['佐倉市八街市酒々井町消防本部', 'http://business4.plala.or.jp/chiba119/web/sakura/annai.html'],
  ['山武広域消防本部', 'http://business4.plala.or.jp/chiba119/web/sanbu/annai.html'],
  ['袖ケ浦市消防本部', 'http://business4.plala.or.jp/chiba119/web/sodegaura/annai.html'],
  ['匝瑳市横芝光町消防本部', 'http://business4.plala.or.jp/chiba119/web/sosa/annai.html'],
  ['富里市消防本部', 'http://business4.plala.or.jp/chiba119/web/tomisato/annai.html'],
  ['四街道市消防本部', 'http://business4.plala.or.jp/chiba119/web/yotsukaido/annai.html'],
  ['栃木市消防本部', 'http://cc9.easypocket.jp/'],
  ['館林消防本部', 'http://cc9.easypocket.jp/'],
  ['駿東伊豆消防本部（伊東市）', 'http://cityito.seesaa.net/category/12759255-1.html'],
  ['村上市消防本部', 'http://e.bme.jp/bm/p/bn/list.php?i=mrkm_ml28&no=all'],
  ['広島市消防局', 'http://enewp9840101.kir.jp/'],
  ['久慈広域消防本部', 'http://fd-kuji.jp/saigai/'],
  ['とかち広域消防局', 'http://fire-tokachi.info/'],
  ['芳賀地区広域消防本部', 'http://hagakouiki.jp/syoubou/'],
  ['東広島市消防局', 'http://higashihiroshima-fd-119.jp/'],
  ['北九州市消防局', 'http://kitakyushu.xpressmail.jp/saigai/navi/'],
  ['粕屋北部消防本部', 'http://m119.city.fukuoka.lg.jp/kasuhoku/hpinfo.html'],
  ['岡山市消防局', 'http://mail119.city.okayama.jp/fire/saigai/saigaipc.html'],
  ['市川市消防局', 'http://mama.city.ichikawa.chiba.jp/saigai/index.html'],
  ['南越消防本部', 'http://message.t-catv.co.jp/kakoview.php?id=7'],
  ['長野市消防局', 'http://nagano-bousai.jp/'],
  ['小田原市消防本部', 'http://odawara-saigai.sakura.ne.jp/saigai/'],
  ['さつま町消防本部', 'http://safety.satsuma-net.jp/app-front/'],
  ['埼玉西部消防局', 'http://saigai.saisei119.jp/index.cgi?page=14&rlist=page%3D1&'],
  ['仙台市消防局', 'http://sendaicity.bosai.info/sendaicity/fireinfo/index.html'],
  ['士別地方消防本部', 'http://shibetsu119.com/top.html'],
  ['上山市消防本部', 'http://shoubo.city.kaminoyama.yamagata.jp/syutsu.htm'],
  ['滝川地区広域消防本部', 'http://takifire.com/saigai_info/index.html'],
  ['天童市消防本部', 'http://tendo-shoubou.jp/'],
  ['苫小牧市消防本部', 'http://tomakomai119.ec-net.jp/'],
  ['宇都宮市消防局', 'http://utsunomiya.mwjp.jp/mobile/index.cgi?page=119'],
  ['伊勢原市消防本部', 'http://www-sa.smart-lgov.jp/material/isehara/history.html'],
  ['札幌市消防局', 'http://www.119.city.sapporo.jp/saigai/sghp.html'],
  ['山口市消防本部', 'http://www.119ymg.jp/jian/jian.html'],
  ['明石市消防本部', 'http://www.akashifd-pri.jp/'],
  ['座間市消防本部', 'http://www.anshin-bousai.net/zama/news_mail/cat561/'],
  ['十日町地域消防本部', 'http://www.ansinmail.jp/list/'],
  ['海老名市消防本部', 'http://www.bousai.city.ebina.kanagawa.jp/www/genre/0000000000000/1000000000024/index.html'],
  ['平戸市消防本部', 'http://www.bousai.city.hirado.nagasaki.jp/index.html'],
  ['甘木・朝倉消防本部', 'http://www.center-chikugo119.jp/fire/saigai/asakuraPcSel.html'],
  ['筑後市消防本部', 'http://www.center-chikugo119.jp/fire/saigai/chikugoPcSel.html'],
  ['久留米広域消防本部', 'http://www.center-chikugo119.jp/fire/saigai/kurumePcSel.html'],
  ['みやま市消防本部', 'http://www.center-chikugo119.jp/fire/saigai/miyamaPcSel.html'],
  ['大川市消防本部', 'http://www.center-chikugo119.jp/fire/saigai/okawaPcSel.html'],
  ['大牟田市消防本部', 'http://www.center-chikugo119.jp/fire/saigai/omutaPcSel.html'],
  ['八女消防本部', 'http://www.center-chikugo119.jp/fire/saigai/yamePcSel.html'],
  ['柳川市消防本部', 'http://www.center-chikugo119.jp/fire/saigai/yanagawaPcSel.html'],
  ['茅ヶ崎市消防本部', 'http://www.chigasaki-samukawa119.info/chigasaki-saigai/index.html'],
  ['筑紫野太宰府消防本部', 'http://www.chikuta119.jp/saigai-info/index.html'],
  ['袋井消防本部', 'http://www.chutoen-shirei.jp/fukuroi/saigai/'],
  ['磐田市消防本部', 'http://www.chutoen-shirei.jp/iwata/saigai/'],
  ['掛川市消防本部', 'http://www.chutoen-shirei.jp/kakegawa/saigai/'],
  ['菊川市消防本部', 'http://www.chutoen-shirei.jp/kikugawa/saigai/'],
  ['御前崎市消防本部', 'http://www.chutoen-shirei.jp/omaezaki/saigai/'],
  ['東大阪市消防局', 'http://www.city.higashiosaka.lg.jp/saigai/saigai.html'],
  ['四日市市消防本部', 'http://www.cty-net.ne.jp/community/areainfo?topics_group_id=82&contents_type=236'],
  ['桑名市消防本部', 'http://www.cty-net.ne.jp/community/areainfo?topics_group_id=82&contents_type=283'],
  ['菰野町消防本部', 'http://www.cty-net.ne.jp/community/areainfo?topics_group_id=82&contents_type=296'],
  ['鳥取県東部広域消防局', 'http://www.east.tottori-119.jp/fire/saigai/saigaipc.html'],
  ['江別市消防本部', 'http://www.ebetsu-fd.jp/'],
  ['東山梨消防本部', 'http://www.ey119.jp/'],
  ['大隅肝属地区消防本部', 'http://www.fd-kimotsuki.jp/'],
  ['鯖江・丹生消防本部', 'http://www.fd-sabaenyu.jp/category/saigai/'],
  ['鶴岡市消防本部', 'http://www.fd-tsuruoka.jp/'],
  ['宮崎市消防局', 'http://www.fire-miyazaki.jp/kpc.htm'],
  ['白山野々市広域消防本部', 'http://www.hakusan-nonoichi.jp/'],
  ['比企広域消防本部', 'http://www.hiki-saitama.jp/119/'],
  ['ひたちなか・東海広域消防本部', 'http://www.hitachinaka-tokai.or.jp/cgi/acmailer3/backnumber.cgi'],
  ['筑西広域消防本部', 'http://www.ibaraki-sirei.jp/saigai/chikusei/annai.html'],
  ['大子町消防本部', 'http://www.ibaraki-sirei.jp/saigai/daigo/annai.html'],
  ['常陸大宮市消防本部', 'http://www.ibaraki-sirei.jp/saigai/hitachiomiya/annai.html'],
  ['常陸太田市消防本部', 'http://www.ibaraki-sirei.jp/saigai/hitachiota/annai.html'],
  ['茨城町消防本部', 'http://www.ibaraki-sirei.jp/saigai/ibaraki/annai.html'],
  ['茨城西南広域消防本部', 'http://www.ibaraki-sirei.jp/saigai/ibarakiseinan/annai.html'],
  ['石岡市消防本部', 'http://www.ibaraki-sirei.jp/saigai/ishioka/annai.html'],
  ['常総広域消防本部', 'http://www.ibaraki-sirei.jp/saigai/joso/annai.html'],
  ['笠間市消防本部', 'http://www.ibaraki-sirei.jp/saigai/kasama/annai.html'],
  ['鹿島消防本部', 'http://www.ibaraki-sirei.jp/saigai/kashima/annai.html'],
  ['かすみがうら市消防本部', 'http://www.ibaraki-sirei.jp/saigai/kasumigaura/annai.html'],
  ['北茨城市消防本部', 'http://www.ibaraki-sirei.jp/saigai/kitaibaraki/annai.html'],
  ['水戸市消防本部', 'http://www.ibaraki-sirei.jp/saigai/mito/annai.html'],
  ['那珂市消防本部', 'http://www.ibaraki-sirei.jp/saigai/naka/annai.html'],
  ['大洗町消防本部', 'http://www.ibaraki-sirei.jp/saigai/oarai/annai.html'],
  ['小美玉市消防本部', 'http://www.ibaraki-sirei.jp/saigai/omitama/annai.html'],
  ['鹿行広域消防本部', 'http://www.ibaraki-sirei.jp/saigai/rokkou/annai.html'],
  ['高萩市消防本部', 'http://www.ibaraki-sirei.jp/saigai/takahagi/annai.html'],
  ['取手市消防本部', 'http://www.ibaraki-sirei.jp/saigai/toride/annai.html'],
  ['土浦市消防本部', 'http://www.ibaraki-sirei.jp/saigai/tuchiura/annai.html'],
  ['飯塚地区消防本部', 'http://www.iizuka119.jp/'],
  ['壱岐市消防本部', 'http://www.ikkr.jp/app/user/42210/history/showHistory.do'],
  ['出雲市消防本部', 'http://www.izumo119.or.jp/~saigai/saigai.html'],
  ['唐津市消防本部', 'http://www.karatsu-bousai.jp/disaster_informations/'],
  ['粕屋南部消防本部', 'http://www.kasuyananbu-shobo.jp/'],
  ['小松市消防本部', 'http://www.kfd119.jp/fire/saigai/saigaipc.html'],
  ['柏原羽曳野藤井寺消防本部', 'http://www.khf119.jp/fire/saigai/saigaiPc.html'],
  ['杵藤地区広域消防本部', 'http://www.kitou-web.jp/disaster/'],
  ['高知市消防局', 'http://www.kochi119.com/p/'],
  ['京都中部広域消防本部', 'http://www.kyoto-chubu119.jp/'],
  ['松本広域消防局', 'http://www.m-kouiki119.jp/matsu/MatsuServ?class_no=1&dbNo=2&size=0'],
  ['長岡市消防本部', 'http://www.nagaoka-fd.com/fire/saigai/saigaipc.html'],
  ['七尾鹿島消防本部', 'http://www.nanaka-fd.jp/home.html'],
  ['新居浜市消防本部', 'http://www.niihama-119.com/'],
  ['奥能登広域圏消防本部', 'http://www.okunoto-fd.jp/honbu_annai.php'],
  ['大津市消防局', 'http://www.otsu119.jp/fire/saigai/saigaiPc.html'],
  ['酒田広域消防本部', 'http://www.sakatashobo.jp/'],
  ['島原広域消防本部', 'http://www.shimabara-area.net/site/'],
  ['春日井市消防本部', 'http://www.syobo.city.kasugai.aichi.jp/syobo/real/kasai.html'],
  ['氷見市消防本部', 'http://www.takaokafire.jp/himi/saigai/index.html'],
  ['高岡市消防本部', 'http://www.takaokafire.jp/takaoka/saigai/index.html'],
  ['砺波地域消防本部', 'http://www.takaokafire.jp/tonami/saigai/index.html'],
  ['蒲郡市消防本部', 'http://www.tousan-fd.jp/gamagori/saigai/index.html'],
  ['新城市消防本部', 'http://www.tousan-fd.jp/shinshiro/saigai/index.html'],
  ['田原市消防本部', 'http://www.tousan-fd.jp/tahara/saigai/index.html'],
  ['豊橋市消防本部', 'http://www.tousan-fd.jp/toyohashi/saigai/index.html'],
  ['豊川市消防本部', 'http://www.tousan-fd.jp/toyokawa/saigai/index.html'],
  ['内灘町消防本部', 'http://www.town.uchinada.ishikawa.jp/osirase/shobo/'],
  ['富山市消防局', 'http://www.toyamafire-dept.jp/saigai.htm'],
  ['湯沢雄勝広域消防本部', 'http://www.yutopia.or.jp/~yokoiki/index.html'],
  ['豊岡市消防本部', 'https://119.city.toyooka.lg.jp/'],
  ['八戸広域消防本部', 'https://anshin.city.hachinohe.aomori.jp/anshinPub/index.html'],
  ['下北地域広域消防本部（むつ市）', 'https://anshin.city.mutsu.lg.jp/category.php?gno=13'],
  ['綾瀬市消防本部', 'https://ayase-city.site.ktaiwork.jp/?cat=4'],
  ['横浜市消防局', 'https://cgi.city.yokohama.lg.jp/shobo/disaster/index.html'],
  ['川崎市消防局', 'https://cgi.city.yokohama.lg.jp/shobo/disaster/index.html'],
  ['長崎県央広域消防本部', 'https://cous.mail-dpt.jp/kenou119/mailinfo.php?cat_no=1'],
  ['山形市消防本部', 'https://cous.mail-dpt.jp/yamagatashobo/mailinfo.php?cat_no=1'],
  ['京都市消防局', 'https://disif.city.kyoto.lg.jp/annai/main/'],
  ['大船渡地区消防本部', 'https://fd-ofunato.jp/kensu/Jian.html'],
  ['金沢市消防局', 'https://fire.city.kanazawa.ishikawa.jp/'],
  ['かほく市消防本部', 'https://fire.city.kanazawa.ishikawa.jp/kahoku/'],
  ['萩市消防本部', 'https://frs.xpressmail.jp/publish/hagi/all'],
  ['美祢市消防本部', 'https://frs.xpressmail.jp/publish/mine/all'],
  ['長門市消防本部', 'https://frs.xpressmail.jp/publish/nagato/all'],
  ['下関市消防局', 'https://frs.xpressmail.jp/publish/shimonoseki/all'],
  ['雲南消防本部', 'https://frs.xpressmail.jp/publish/unnan_fire/all'],
  ['春日・大野城・那珂川消防本部', 'https://fukuoka.kon119.or.jp/'],
  ['葉山町消防本部', 'https://hayama.fire.yokosuka.kanagawa.jp/saigai/hayama.html'],
  ['上越地域消防局（上越市）', 'https://joetsu-city.site.ktaiwork.jp/category/%E7%81%AB%E7%81%BD%E6%83%85%E5%A0%B1/'],
  ['鹿児島市消防局', 'https://kagoshima-city-fd.site.ktaiwork.jp/'],
  ['気仙沼・本吉地域広域消防本部', 'https://km-fire.jp/category/saigai'],
  ['湖北地域消防本部', 'https://kohoku-fd.site.ktaiwork.jp/'],
  ['宗像地区消防本部', 'https://m119.city.fukuoka.lg.jp/munakata/hpinfo.html'],
  ['前橋市消防局', 'https://maebashi-city.site.ktaiwork.jp/'],
  ['千曲坂城消防本部（千曲市）', 'https://mail.cous.jp/chikuma/'],
  ['姫路市消防局', 'https://mail.cous.jp/himeji119/'],
  ['いわき市消防本部', 'https://mail.cous.jp/iwaki/'],
  ['勝山市消防本部', 'https://mail.cous.jp/katsuyama/'],
  ['湖南広域消防局', 'https://mail.cous.jp/konanfd/'],
  ['栗原市消防本部', 'https://mail.cous.jp/kuriharacity/'],
  ['登米市消防本部', 'https://mail.cous.jp/tomecity/'],
  ['生駒市消防本部', 'https://nara119.jp/fire/saigai/saigaipcIkoma.html'],
  ['奈良市消防局', 'https://nara119.jp/fire/saigai/saigaipcNara.html'],
  ['新潟市消防局', 'https://niigata119.city.niigata.lg.jp/'],
  ['太田市消防本部', 'https://ota-city.site.ktaiwork.jp/'],
  ['富士市消防本部', 'https://plus.sugumail.com/usr/fuji/doc?tag_id=1717'],
  ['富士宮市消防本部', 'https://plus.sugumail.com/usr/fujinomiya/doc?tag_id=64'],
  ['船橋市消防局', 'https://plus.sugumail.com/usr/funabashi/doc?tag_id=658'],
  ['岐阜市消防本部', 'https://plus.sugumail.com/usr/gifu-city/doc?tag_id=1047'],
  ['糸魚川市消防本部', 'https://plus.sugumail.com/usr/itoigawa/doc?tag_id=1366'],
  ['海津市消防本部', 'https://plus.sugumail.com/usr/kaizu/doc?tag_id=1307'],
  ['三原市消防本部', 'https://plus.sugumail.com/usr/mihara/doc?tag_id=1064'],
  ['中津川市消防本部', 'https://plus.sugumail.com/usr/nakatsugawa/doc?tag_id=215'],
  ['日南市消防本部', 'https://plus.sugumail.com/usr/nichinan/doc?tag_id=903'],
  ['諏訪広域消防本部（岡谷市）', 'https://plus.sugumail.com/usr/okaya/doc?tag_id=1649'],
  ['江南市消防本部', 'https://service.sugumail.com/aichi-konan/member/portals/list_mail/6034'],
  ['綾部市消防本部', 'https://service.sugumail.com/ayabe/member/portals/list_mail/2383'],
  ['浜松市消防局', 'https://service.sugumail.com/bosai-hotmail-hamamatsu/member/portals/list_mail/5895'],
  ['秩父消防本部', 'https://service.sugumail.com/chichibu/member/portals/list_mail/1096'],
  ['羽島市消防本部', 'https://service.sugumail.com/hashima/member/portals/list_mail/5749'],
  ['伊勢市消防本部', 'https://service.sugumail.com/ise/member/portals/list_mail/1015'],
  ['川口市消防局', 'https://service.sugumail.com/kawaguchi/member/portals/list_mail/5175'],
  ['桐生市消防本部', 'https://service.sugumail.com/kiryu/member/portals/list_mail/4801'],
  ['熊本市消防局', 'https://service.sugumail.com/kumamoto/member/portals/list_mail/6639'],
  ['松戸市消防局', 'https://service.sugumail.com/matsudo/member/portals/list_mail/1242'],
  ['富山県東部消防本部（滑川市）', 'https://service.sugumail.com/namerikawa/member/portals/list_mail/5844'],
  ['習志野市消防本部', 'https://service.sugumail.com/narashino/member/portals/list_mail/874'],
  ['那須地区消防本部（那須塩原市）', 'https://service.sugumail.com/nasushiobara/member/portals/list_mail/1749'],
  ['那須地区消防本部（大田原市）', 'https://service.sugumail.com/ohtawara/member/portals/list_mail/5652'],
  ['佐世保市消防局', 'https://service.sugumail.com/sasebo-shimin/member/portals/list_mail/7094'],
  ['多治見市消防本部', 'https://service.sugumail.com/tajimi/member/portals/list_mail/1265'],
  ['高島市消防本部', 'https://service.sugumail.com/takashima/member/portals/list_mail/5321'],
  ['八千代市消防本部', 'https://service.sugumail.com/yachiyo/member/portals/list_mail/4853'],
  ['吾妻広域消防本部', 'https://takasaki-119-center.jp/center/saigai_azuma.html'],
  ['渋川広域消防本部', 'https://takasaki-119-center.jp/center/saigai_sibukawa.html'],
  ['高崎市等広域消防局', 'https://takasaki-119-center.jp/center/saigai_takasaki.html'],
  ['多野藤岡広域消防本部', 'https://takasaki-119-center.jp/center/saigai_tanofujioka.html'],
  ['富岡甘楽広域消防本部', 'https://takasaki-119-center.jp/center/saigai_tomiokakanra.html'],
  ['利根沼田広域消防本部', 'https://takasaki-119-center.jp/center/saigai_tonenumata.html'],
  ['上田地域広域消防本部（上田市）', 'https://ueda-city.site.ktaiwork.jp/?cat=6'],
  ['宇和島地区広域消防本部', 'https://uwajima-city.site.ktaiwork.jp/?cat=5'],
  ['川越地区消防局', 'https://www.119kawagoechiku.jp/index.html'],
  ['三沢市消防本部', 'https://www.bousai-misawa.jp/misawaPub/index.html'],
  ['鳥取県中部広域消防局', 'https://www.chubu-furusato-tottori.jp/category/dis-info'],
  ['阿賀野市消防本部', 'https://www.city.agano.niigata.jp/kurashi_tetsuzuki/anzen_anshin/aganoshishobohombu/syutudo_119/index.html'],
  ['上尾市消防本部', 'https://www.city.ageo.lg.jp/mailmaga/web_list.php?selMMNM=9'],
  ['秋田市消防本部', 'https://www.city.akita.lg.jp/bosai-kinkyu/kasai/index.html'],
  ['福岡市消防局', 'https://www.city.fukuoka.lg.jp/syobo/index.html'],
  ['福島市消防本部', 'https://www.city.fukushima.fukushima.jp/syoubou-top/shobo/shobohonbu/index.html'],
  ['福山地区消防局', 'https://www.city.fukuyama.hiroshima.jp/shobokumiai/home/fire_list.html'],
  ['函館市消防本部', 'https://www.city.hakodate.hokkaido.jp/docs/2016050900014/'],
  ['花巻市消防本部', 'https://www.city.hanamaki.iwate.jp/kurashi/anshin_anzen/bousai_saigai/1004524.html'],
  ['飛騨市消防本部', 'https://www.city.hida.gifu.jp/soshiki/list3-1.html'],
  ['池田市消防本部', 'https://www.city.ikeda.osaka.jp/section/syutsujyo.shtml'],
  ['射水市消防本部', 'https://www.city.imizu.toyama.jp/emg/emgInfoList.aspx'],
  ['柏市消防局', 'https://www.city.kashiwa.lg.jp/fdk/disaster/index.html'],
  ['神戸市消防局', 'https://www.city.kobe.lg.jp/a17109/bosai/shobo/kasai.html'],
  ['湖西市消防本部', 'https://www.city.kosai.shizuoka.jp/cgi-bin/smart_alert.php/1/list?page=1&continue=1'],
  ['南魚沼市消防本部', 'https://www.city.minamiuonuma.niigata.jp/shoubouhonbu/docs/disaster_info.html'],
  ['上越地域消防局（妙高市）', 'https://www.city.myoko.niigata.jp/urgency/'],
  ['根室市消防本部', 'https://www.city.nemuro.hokkaido.jp/lifeinfo/kakuka/syoubou/shoubousho/kyuukyuutushin/oshirase/605.html'],
  ['日光市消防本部', 'https://www.city.nikko.lg.jp/tsuushin/guide/shoubou/shutsudou/saishin.html'],
  ['小野市消防本部', 'https://www.city.ono.hyogo.jp/section/Jian.html'],
  ['高山市消防本部', 'https://www.city.takayama.lg.jp/bousai/shoubo.html'],
  ['徳島市消防局', 'https://www.city.tokushima.tokushima.jp/anzen/shoubo_bousai/shoubou/shoubou_information/dipatch_information/450201a20094318543.html'],
  ['魚沼市消防本部', 'https://www.city.uonuma.niigata.jp/fd/'],
  ['稲敷広域消防本部（牛久市）', 'https://www.city.ushiku.lg.jp/mm_pro/index.php?mode=backnumber&code=1'],
  ['伊達地方消防本部', 'https://www.date119.jp/control/?cat=6'],
  ['高槻市消防本部', 'https://www.fd-takatsuki.jp/119'],
  ['稲城市消防本部', 'https://www.ikkr.jp/app/user/13225/history/showHistory.do?pageId=0&om=1&categoryId=598'],
  ['愛川町消防本部', 'https://www.ikkr.jp/app/user/14401/history/showHistory.do?categoryId=868'],
  ['赤磐市消防本部', 'https://www.ikkr.jp/app/user/33213/history/showHistory.do?om=1'],
  ['十和田市消防本部', 'https://www.info-towada.jp/towadaPub/index.html'],
  ['石狩北部地区消防本部', 'https://www.ishikarihokubu.jp/emergency/Jian.html'],
  ['埼玉県央広域消防本部', 'https://www.ken-o.or.jp/firehead/index.html'],
  ['衣浦東部広域消防局', 'https://www.kinutoh.jp/'],
  ['松江市消防本部', 'https://www.m.shirei-saigai-jyouhou.sd.web-sanin.jp/index.html'],
  ['舞鶴市消防本部', 'https://www.maizuru119.com/'],
  ['奈良県広域消防本部', 'https://www.naraksk119.jp/'],
  ['西宮市消防局', 'https://www.nishinomiya-bousai.jp/firedept/'],
  ['郡山地方広域消防本部', 'https://www.shobo.koriyama.fukushima.jp/saigai/index.html'],
  ['須賀川広域消防本部', 'https://www.sukagawa119.jp/saigai/'],
  ['鳥取県西部広域消防局', 'https://www.tottori-seibukoiki.jp/syobo/index.htm'],
  ['那須地区消防本部（那須町）', 'https://www.town.nasu.lg.jp/viewer/disaster.html?idSubTop=2'],
  ['津幡町消防本部', 'https://www.town.tsubata.lg.jp/'],
  ['燕・弥彦消防本部', 'https://www.tysogo.jp/'],
  ['若狭消防本部', 'https://www.wakasa-fd.jp/'],
  ['旭川市消防本部', 'https://www1.city.asahikawa.hokkaido.jp/bousai/syutsudou.htm'],
  ['一関市消防本部', 'https://x.bmd.jp/bm/p/bn/list.php?i=ichinoseki_shobo&no=all'],
  ['横須賀市消防局', 'https://yokosuka.fire.yokosuka.kanagawa.jp/saigai/yokosuka.html'],
  ['深谷市消防本部', 'http://www.city.fukaya.saitama.jp/shobo/index.html'],
  ['平塚市消防本部', 'https://www.city.hiratsuka.kanagawa.jp/shobo/index.html'],
  ['大磯町消防本部', 'http://www.town.oiso.kanagawa.jp/kurashi/shoubou/index.html'],
  ['二宮町消防本部', 'http://www.town.ninomiya.kanagawa.jp/soshiki/shobohonbu/shobo/shomu/s02/1441761942656.html'],
  ['紋別地区消防本部', 'https://mombetsu.jp/soshiki/shoubou/'],
  ['根室北部消防本部', 'https://www.nakashibetsu.jp/kurashi/bohanbosai/shobo/'],
  ['大館市消防本部', 'http://fd-odate.la.coocan.jp/'],
  ['安達地方広域消防本部', 'https://www.adachikouiki.lg.jp/site/shobo/'],
  ['入間東部地区消防本部', 'https://www.irumatohbu119.jp/shobo/'],
  ['坂戸・鶴ヶ島市消防本部', 'http://sakatsuru119.jp/'],
  ['流山市消防本部', 'https://www.city.nagareyama.chiba.jp/section/1031740/index.html'],
  ['加賀市消防本部', 'https://www.city.kaga.ishikawa.jp/soshiki/shobo/index.html'],
  ['甲府広域消防本部', 'http://www.kfd.or.jp/'],
  ['北アルプス広域消防本部', 'http://www.kita-alps.omachi.nagano.jp/gyoumu/syoubou.html'],
  ['諏訪広域消防本部', 'https://www.union.suwa.lg.jp/site/shobo/'],
  ['亀山市消防本部', 'https://www.city.kameyama.mie.jp/shobo/'],
  ['泉大津市消防本部', 'https://www.city.izumiotsu.lg.jp/syoubou/index.html'],
  ['江田島市消防本部', 'https://www.city.etajima.hiroshima.jp/cms/categories/show/188'],
  ['八幡浜地区消防本部', 'http://fd-yawatahama-ehime.jp/'],
]);

async function postHandler(page: Page): Promise<Post[]> {
  const posts: Post[] = [];
  await page.waitForSelector('table.visible-sm', { visible: true });
  /* eslint-disable no-await-in-loop */
  const elementHandles: ElementHandle[] = await page.$$('table.visible-sm tbody tr');
  for (let i = 0; i < elementHandles.length; i++) {
    const dateText = await elementHandles[i].$eval('td:nth-child(5) .pull-right', (node) => node.textContent?.trim().replace(/\n+/g, ''));
    const date = moment(dateText, 'MM-DD hh:mm').format('MM/DD/YYYY hh:mm');
    if (!moment(date, 'MM/DD/YYYY hh:mm').isSame(moment(), 'day')) return posts;
    const fireDepartment = await elementHandles[i].$eval('td:nth-child(1) a', (node) => node.textContent?.trim().replace(/\n+/g, ''));
    const linkMap = referenceMap.get(fireDepartment!);
    const caseName = await elementHandles[i].$eval('td:nth-child(2)', (node) => node.textContent?.trim().replace(/\n+/g, ''));
    const status = await elementHandles[i].$eval('td:nth-child(3)', (node) => node.textContent?.trim().replace(/\n+/g, ''));
    const timesOfDay = await elementHandles[i].$eval('td:nth-child(4)', (node) => node.textContent?.trim().replace(/\n+/g, ''));
    const details = await elementHandles[i].$eval('td:nth-child(5) a', (node) => node.textContent?.trim().replace(/\n+/g, '').replace(/\t+/g, ''));
    const timestamp = moment(date, 'MM/DD/YYYY hh:mm').unix();
    const articleInfo = `${caseName}:${status}; ${timesOfDay}; ${details}; ${fireDepartment}`;
    const extraDataInfo = {
      fireDepartment,
      caseName,
      status,
      timesOfDay,
      details,
      ingestpurpose: 'mdsbackup',
    };
    posts.push(
      new Post({
        text: articleInfo,
        postedAt: timestamp,
        postUrl: linkMap,
        extraData: extraDataInfo,
      }),
    );
  }
  return posts;
}

export const parser = new PuppeteerParser(
  'MK - Mode',
  baseURLPrefix,
  [
    {
      parser: postHandler,
      name: 'post',
    },
  ],
  baseURLSuffix,
);
